use std::sync::Arc;

use async_trait::async_trait;
use pgvector::Vector;
use sqlx::Row;
use uuid::Uuid;

use crate::error::CherubError;
use crate::storage::embedding::EmbeddingProvider;
use crate::storage::search::{RankedResult, SearchConfig, reciprocal_rank_fusion};
use crate::storage::{Memory, MemoryFilter, MemoryScope, MemoryStore, MemoryUpdate, NewMemory};

use super::Pool;

/// PostgreSQL implementation of `MemoryStore`.
///
/// Uses the `memories` table from the initial migration. IDs are generated by the
/// database using `uuidv7()` (PG 18 built-in) and returned via RETURNING.
///
/// Hybrid search (M6c): when an `EmbeddingProvider` is configured, `search()`
/// runs both FTS and vector queries and fuses the results using Reciprocal Rank
/// Fusion. Without an embedder, `search()` falls back to FTS-only (M6b behavior).
pub struct PgMemoryStore {
    pool: Pool,
    /// Present when an `OPENAI_API_KEY` is configured. `None` = FTS-only search.
    embedder: Option<Arc<dyn EmbeddingProvider>>,
}

impl PgMemoryStore {
    /// Create a store with FTS-only search. Backward-compatible with M6b callers.
    pub fn new(pool: Pool) -> Self {
        Self {
            pool,
            embedder: None,
        }
    }

    /// Create a store with hybrid search enabled.
    pub fn with_embedder(pool: Pool, embedder: Arc<dyn EmbeddingProvider>) -> Self {
        Self {
            pool,
            embedder: Some(embedder),
        }
    }

    fn query_err(e: impl std::fmt::Display) -> CherubError {
        CherubError::Storage(format!("query error: {e}"))
    }

    /// Try to embed `text`. Returns `None` on failure (logs a warning) so that
    /// callers can degrade gracefully rather than failing the entire operation.
    async fn try_embed(&self, text: &str) -> Option<Vec<f32>> {
        let embedder = self.embedder.as_ref()?;
        match embedder.embed(text).await {
            Ok(v) => Some(v),
            Err(e) => {
                tracing::warn!(error = %e, "embedding failed, storing without vector");
                None
            }
        }
    }

    /// FTS search: returns `RankedResult`s with 1-based positional rank.
    async fn fts_search(
        &self,
        query: &str,
        scope: Option<MemoryScope>,
        user_id: Option<&str>,
        limit: usize,
    ) -> Result<Vec<RankedResult>, CherubError> {
        let mut qb = sqlx::QueryBuilder::new(
            "SELECT id, confidence FROM memories \
             WHERE superseded_by IS NULL AND tsv @@ plainto_tsquery('english', ",
        );
        qb.push_bind(query.to_owned()).push(")");

        if let Some(s) = scope {
            qb.push(" AND scope = ").push_bind(s.as_str().to_owned());
        }
        if let Some(uid) = user_id {
            qb.push(" AND user_id = ").push_bind(uid.to_owned());
        }

        qb.push(" ORDER BY ts_rank(tsv, plainto_tsquery('english', ")
            .push_bind(query.to_owned())
            .push(")) DESC LIMIT ")
            .push_bind(limit as i64);

        let rows = qb
            .build()
            .fetch_all(&self.pool)
            .await
            .map_err(Self::query_err)?;

        Ok(rows
            .iter()
            .enumerate()
            .map(|(i, row)| RankedResult {
                memory_id: row.get("id"),
                rank: i + 1,
                confidence: row.get::<f32, _>("confidence"),
            })
            .collect())
    }

    /// Vector search: returns `RankedResult`s ordered by cosine distance.
    /// Returns an empty vec if no embedder is configured or embedding fails.
    async fn vector_search(
        &self,
        query: &str,
        scope: Option<MemoryScope>,
        user_id: Option<&str>,
        limit: usize,
    ) -> Result<Vec<RankedResult>, CherubError> {
        let query_vec = match self.try_embed(query).await {
            Some(v) => Vector::from(v),
            None => return Ok(Vec::new()),
        };

        let mut qb = sqlx::QueryBuilder::new(
            "SELECT id, confidence FROM memories \
             WHERE superseded_by IS NULL AND embedding IS NOT NULL",
        );

        if let Some(s) = scope {
            qb.push(" AND scope = ").push_bind(s.as_str().to_owned());
        }
        if let Some(uid) = user_id {
            qb.push(" AND user_id = ").push_bind(uid.to_owned());
        }

        qb.push(" ORDER BY embedding <=> ")
            .push_bind(query_vec)
            .push(" LIMIT ")
            .push_bind(limit as i64);

        let rows = qb
            .build()
            .fetch_all(&self.pool)
            .await
            .map_err(Self::query_err)?;

        Ok(rows
            .iter()
            .enumerate()
            .map(|(i, row)| RankedResult {
                memory_id: row.get("id"),
                rank: i + 1,
                confidence: row.get::<f32, _>("confidence"),
            })
            .collect())
    }

    /// Bulk-load full `Memory` rows by a list of IDs in one query.
    /// Returns rows in the order specified by `ids` (preserves RRF score order).
    async fn load_memories_by_ids(&self, ids: &[Uuid]) -> Result<Vec<Memory>, CherubError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }

        let rows = sqlx::query(&format!(
            "SELECT {MEMORY_COLUMNS} FROM memories WHERE id = ANY($1)"
        ))
        .bind(ids)
        .fetch_all(&self.pool)
        .await
        .map_err(Self::query_err)?;

        // Build an id→Memory map then reorder according to the input slice.
        let by_id: std::collections::HashMap<Uuid, Memory> = rows
            .iter()
            .map(|row| map_row(row).map(|m| (m.id, m)))
            .collect::<Result<_, _>>()?;

        Ok(ids.iter().filter_map(|id| by_id.get(id).cloned()).collect())
    }
}

/// Standard column list for SELECT queries that produce a `Memory`.
const MEMORY_COLUMNS: &str = "id, user_id, scope, category, path, content, structured, \
     source_session_id, source_turn_number, source_type, confidence, \
     created_at, updated_at, last_referenced_at, superseded_by";

/// Map a postgres `Row` to a `Memory` struct. Parses TEXT enum columns from strings.
fn map_row(row: &sqlx::postgres::PgRow) -> Result<Memory, CherubError> {
    let scope_str: String = row.get("scope");
    let category_str: String = row.get("category");
    let source_type_str: String = row.get("source_type");

    // REAL column in PG maps to f32 in sqlx.
    let confidence: f32 = row.get("confidence");

    Ok(Memory {
        id: row.get("id"),
        user_id: row.get::<String, _>("user_id"),
        scope: scope_str.parse()?,
        category: category_str.parse()?,
        path: row.get::<String, _>("path"),
        content: row.get::<String, _>("content"),
        structured: row.get("structured"),
        source_session_id: row.get("source_session_id"),
        source_turn_number: row.get("source_turn_number"),
        source_type: source_type_str.parse()?,
        confidence,
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
        last_referenced_at: row.get("last_referenced_at"),
        superseded_by: row.get("superseded_by"),
    })
}

#[async_trait]
impl MemoryStore for PgMemoryStore {
    async fn store(&self, memory: NewMemory) -> Result<Uuid, CherubError> {
        // Embed before running the query so we don't hold pool connections during HTTP.
        let embedding = self.try_embed(&memory.content).await.map(Vector::from);

        let row = sqlx::query(
            "INSERT INTO memories \
             (user_id, scope, category, path, content, structured, \
              source_session_id, source_turn_number, source_type, confidence, embedding) \
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) \
             RETURNING id",
        )
        .bind(&memory.user_id)
        .bind(memory.scope.as_str())
        .bind(memory.category.as_str())
        .bind(&memory.path)
        .bind(&memory.content)
        .bind(&memory.structured)
        .bind(memory.source_session_id)
        .bind(memory.source_turn_number)
        .bind(memory.source_type.as_str())
        .bind(memory.confidence)
        .bind(&embedding)
        .fetch_one(&self.pool)
        .await
        .map_err(Self::query_err)?;

        Ok(row.get("id"))
    }

    async fn recall(&self, filter: MemoryFilter) -> Result<Vec<Memory>, CherubError> {
        // Build WHERE clauses dynamically. Always exclude superseded records.
        let mut qb = sqlx::QueryBuilder::new(format!(
            "SELECT {MEMORY_COLUMNS} FROM memories WHERE superseded_by IS NULL"
        ));

        if let Some(scope) = filter.scope {
            qb.push(" AND scope = ")
                .push_bind(scope.as_str().to_owned());
        }
        if let Some(cat) = filter.category {
            qb.push(" AND category = ")
                .push_bind(cat.as_str().to_owned());
        }
        if let Some(prefix) = filter.path_prefix {
            qb.push(" AND path LIKE ").push_bind(format!("{prefix}%"));
        }
        if let Some(uid) = filter.user_id {
            qb.push(" AND user_id = ").push_bind(uid);
        }

        let limit = filter.limit.unwrap_or(10);
        qb.push(" ORDER BY created_at DESC LIMIT ").push_bind(limit);

        let rows = qb
            .build()
            .fetch_all(&self.pool)
            .await
            .map_err(Self::query_err)?;

        rows.iter().map(map_row).collect()
    }

    async fn search(
        &self,
        query: &str,
        scope: Option<MemoryScope>,
        user_id: Option<&str>,
        limit: i64,
    ) -> Result<Vec<Memory>, CherubError> {
        let config = SearchConfig::default();
        let pre_limit = config.pre_fusion_limit;

        // Run FTS and vector searches. sqlx manages pool connections internally.
        let fts_results = self.fts_search(query, scope, user_id, pre_limit).await?;

        let vector_results = if self.embedder.is_some() {
            self.vector_search(query, scope, user_id, pre_limit).await?
        } else {
            Vec::new()
        };

        let scored = reciprocal_rank_fusion(&fts_results, &vector_results, &config, limit as usize);

        let ids: Vec<Uuid> = scored.iter().map(|r| r.memory_id).collect();
        self.load_memories_by_ids(&ids).await
    }

    async fn update(&self, id: Uuid, changes: MemoryUpdate) -> Result<Uuid, CherubError> {
        // Load the existing memory to carry forward unchanged fields.
        let existing = sqlx::query(&format!(
            "SELECT {MEMORY_COLUMNS} FROM memories WHERE id = $1"
        ))
        .bind(id)
        .fetch_one(&self.pool)
        .await
        .map_err(Self::query_err)?;
        let base = map_row(&existing)?;

        let new_content = changes
            .content
            .as_deref()
            .unwrap_or(&base.content)
            .to_owned();
        let new_structured = changes.structured.or(base.structured);
        let new_confidence = changes.confidence.unwrap_or(base.confidence);

        // Re-embed new content before inserting.
        let embedding = self.try_embed(&new_content).await.map(Vector::from);

        // Insert new row (DB assigns fresh uuidv7 ID).
        let new_row = sqlx::query(
            "INSERT INTO memories \
             (user_id, scope, category, path, content, structured, \
              source_session_id, source_turn_number, source_type, confidence, embedding) \
             VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) \
             RETURNING id",
        )
        .bind(&base.user_id)
        .bind(base.scope.as_str())
        .bind(base.category.as_str())
        .bind(&base.path)
        .bind(&new_content)
        .bind(&new_structured)
        .bind(base.source_session_id)
        .bind(base.source_turn_number)
        .bind(base.source_type.as_str())
        .bind(new_confidence)
        .bind(&embedding)
        .fetch_one(&self.pool)
        .await
        .map_err(Self::query_err)?;
        let new_id: Uuid = new_row.get("id");

        // Chain the superseded_by pointer on the old row.
        sqlx::query("UPDATE memories SET superseded_by = $1, updated_at = now() WHERE id = $2")
            .bind(new_id)
            .bind(id)
            .execute(&self.pool)
            .await
            .map_err(Self::query_err)?;

        Ok(new_id)
    }

    async fn forget(&self, id: Uuid) -> Result<(), CherubError> {
        // Soft-delete: set superseded_by = self as sentinel (preserves audit trail).
        sqlx::query("UPDATE memories SET superseded_by = id, updated_at = now() WHERE id = $1")
            .bind(id)
            .execute(&self.pool)
            .await
            .map_err(Self::query_err)?;

        Ok(())
    }

    async fn touch(&self, id: Uuid) -> Result<(), CherubError> {
        sqlx::query("UPDATE memories SET last_referenced_at = now() WHERE id = $1")
            .bind(id)
            .execute(&self.pool)
            .await
            .map_err(Self::query_err)?;

        Ok(())
    }
}
