use async_trait::async_trait;
use deadpool_postgres::Pool;
use uuid::Uuid;

use crate::error::CherubError;
use crate::storage::{Memory, MemoryFilter, MemoryScope, MemoryStore, MemoryUpdate, NewMemory};

/// PostgreSQL implementation of `MemoryStore`.
///
/// Uses the `memories` table from V1 migration. IDs are generated by the
/// database using `uuidv7()` (PG 18 built-in) and returned via RETURNING.
pub struct PgMemoryStore {
    pool: Pool,
}

impl PgMemoryStore {
    pub fn new(pool: Pool) -> Self {
        Self { pool }
    }

    fn pool_err(e: impl std::fmt::Display) -> CherubError {
        CherubError::Storage(format!("pool error: {e}"))
    }

    fn query_err(e: impl std::fmt::Display) -> CherubError {
        CherubError::Storage(format!("query error: {e}"))
    }
}

/// Standard column list for SELECT queries that produce a `Memory`.
const MEMORY_COLUMNS: &str = "id, user_id, scope, category, path, content, structured, \
     source_session_id, source_turn_number, source_type, confidence, \
     created_at, updated_at, last_referenced_at, superseded_by";

/// Map a postgres `Row` to a `Memory` struct. Parses TEXT enum columns from strings.
fn map_row(row: &tokio_postgres::Row) -> Result<Memory, CherubError> {
    let scope_str: &str = row.get("scope");
    let category_str: &str = row.get("category");
    let source_type_str: &str = row.get("source_type");

    // REAL column in PG maps to f32 in tokio-postgres.
    let confidence: f32 = row.get("confidence");

    Ok(Memory {
        id: row.get("id"),
        user_id: row.get::<_, String>("user_id"),
        scope: scope_str.parse()?,
        category: category_str.parse()?,
        path: row.get::<_, String>("path"),
        content: row.get::<_, String>("content"),
        structured: row.get("structured"),
        source_session_id: row.get("source_session_id"),
        source_turn_number: row.get("source_turn_number"),
        source_type: source_type_str.parse()?,
        confidence,
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
        last_referenced_at: row.get("last_referenced_at"),
        superseded_by: row.get("superseded_by"),
    })
}

#[async_trait]
impl MemoryStore for PgMemoryStore {
    async fn store(&self, memory: NewMemory) -> Result<Uuid, CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        let row = conn
            .query_one(
                "INSERT INTO memories \
                 (user_id, scope, category, path, content, structured, \
                  source_session_id, source_turn_number, source_type, confidence) \
                 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) \
                 RETURNING id",
                &[
                    &memory.user_id,
                    &memory.scope.as_str(),
                    &memory.category.as_str(),
                    &memory.path,
                    &memory.content,
                    &memory.structured,
                    &memory.source_session_id,
                    &memory.source_turn_number,
                    &memory.source_type.as_str(),
                    &memory.confidence,
                ],
            )
            .await
            .map_err(Self::query_err)?;

        Ok(row.get(0))
    }

    async fn recall(&self, filter: MemoryFilter) -> Result<Vec<Memory>, CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Build WHERE clauses dynamically. Always exclude superseded records.
        // Each param is boxed into a type-erased ToSql so we can mix types.
        let mut conditions: Vec<String> = vec!["superseded_by IS NULL".to_owned()];
        let mut params: Vec<Box<dyn tokio_postgres::types::ToSql + Sync + Send>> = Vec::new();
        let mut idx: usize = 1;

        if let Some(scope) = filter.scope {
            conditions.push(format!("scope = ${idx}"));
            params.push(Box::new(scope.as_str().to_owned()));
            idx += 1;
        }
        if let Some(cat) = filter.category {
            conditions.push(format!("category = ${idx}"));
            params.push(Box::new(cat.as_str().to_owned()));
            idx += 1;
        }
        if let Some(prefix) = filter.path_prefix {
            conditions.push(format!("path LIKE ${idx}"));
            params.push(Box::new(format!("{prefix}%")));
            idx += 1;
        }
        if let Some(uid) = filter.user_id {
            conditions.push(format!("user_id = ${idx}"));
            params.push(Box::new(uid));
            idx += 1;
        }

        let limit = filter.limit.unwrap_or(10);
        let where_clause = conditions.join(" AND ");
        let sql = format!(
            "SELECT {MEMORY_COLUMNS} FROM memories \
             WHERE {where_clause} \
             ORDER BY created_at DESC \
             LIMIT ${idx}"
        );
        params.push(Box::new(limit));

        let param_refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = params
            .iter()
            .map(|p| p.as_ref() as &(dyn tokio_postgres::types::ToSql + Sync))
            .collect();

        let rows = conn
            .query(sql.as_str(), &param_refs)
            .await
            .map_err(Self::query_err)?;

        rows.iter().map(map_row).collect()
    }

    async fn search(
        &self,
        query: &str,
        scope: Option<MemoryScope>,
        user_id: Option<&str>,
        limit: i64,
    ) -> Result<Vec<Memory>, CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        let mut conditions: Vec<String> = vec![
            "superseded_by IS NULL".to_owned(),
            "tsv @@ plainto_tsquery('english', $1)".to_owned(),
        ];
        let mut params: Vec<Box<dyn tokio_postgres::types::ToSql + Sync + Send>> =
            vec![Box::new(query.to_owned())];
        let mut idx: usize = 2;

        if let Some(s) = scope {
            conditions.push(format!("scope = ${idx}"));
            params.push(Box::new(s.as_str().to_owned()));
            idx += 1;
        }
        if let Some(uid) = user_id {
            conditions.push(format!("user_id = ${idx}"));
            params.push(Box::new(uid.to_owned()));
            idx += 1;
        }

        let where_clause = conditions.join(" AND ");
        let sql = format!(
            "SELECT {MEMORY_COLUMNS} FROM memories \
             WHERE {where_clause} \
             ORDER BY ts_rank(tsv, plainto_tsquery('english', $1)) DESC \
             LIMIT ${idx}"
        );
        params.push(Box::new(limit));

        let param_refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = params
            .iter()
            .map(|p| p.as_ref() as &(dyn tokio_postgres::types::ToSql + Sync))
            .collect();

        let rows = conn
            .query(sql.as_str(), &param_refs)
            .await
            .map_err(Self::query_err)?;

        rows.iter().map(map_row).collect()
    }

    async fn update(&self, id: Uuid, changes: MemoryUpdate) -> Result<Uuid, CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Load the existing memory to carry forward unchanged fields.
        let existing = conn
            .query_one(
                &format!("SELECT {MEMORY_COLUMNS} FROM memories WHERE id = $1"),
                &[&id],
            )
            .await
            .map_err(Self::query_err)?;
        let base = map_row(&existing)?;

        let new_content = changes
            .content
            .as_deref()
            .unwrap_or(&base.content)
            .to_owned();
        let new_structured = changes.structured.or(base.structured);
        let new_confidence = changes.confidence.unwrap_or(base.confidence);

        // Insert new row (DB assigns fresh uuidv7 ID).
        let new_row = conn
            .query_one(
                "INSERT INTO memories \
                 (user_id, scope, category, path, content, structured, \
                  source_session_id, source_turn_number, source_type, confidence) \
                 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) \
                 RETURNING id",
                &[
                    &base.user_id,
                    &base.scope.as_str(),
                    &base.category.as_str(),
                    &base.path,
                    &new_content,
                    &new_structured,
                    &base.source_session_id,
                    &base.source_turn_number,
                    &base.source_type.as_str(),
                    &new_confidence,
                ],
            )
            .await
            .map_err(Self::query_err)?;
        let new_id: Uuid = new_row.get(0);

        // Chain the superseded_by pointer on the old row.
        conn.execute(
            "UPDATE memories SET superseded_by = $1, updated_at = now() WHERE id = $2",
            &[&new_id, &id],
        )
        .await
        .map_err(Self::query_err)?;

        Ok(new_id)
    }

    async fn forget(&self, id: Uuid) -> Result<(), CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Soft-delete: set superseded_by = self as sentinel (preserves audit trail).
        conn.execute(
            "UPDATE memories SET superseded_by = id, updated_at = now() WHERE id = $1",
            &[&id],
        )
        .await
        .map_err(Self::query_err)?;

        Ok(())
    }

    async fn touch(&self, id: Uuid) -> Result<(), CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        conn.execute(
            "UPDATE memories SET last_referenced_at = now() WHERE id = $1",
            &[&id],
        )
        .await
        .map_err(Self::query_err)?;

        Ok(())
    }
}
