use std::sync::Arc;

use async_trait::async_trait;
use deadpool_postgres::Pool;
use pgvector::Vector;
use uuid::Uuid;

use crate::error::CherubError;
use crate::storage::embedding::EmbeddingProvider;
use crate::storage::search::{RankedResult, SearchConfig, reciprocal_rank_fusion};
use crate::storage::{Memory, MemoryFilter, MemoryScope, MemoryStore, MemoryUpdate, NewMemory};

/// PostgreSQL implementation of `MemoryStore`.
///
/// Uses the `memories` table from V1 migration. IDs are generated by the
/// database using `uuidv7()` (PG 18 built-in) and returned via RETURNING.
///
/// Hybrid search (M6c): when an `EmbeddingProvider` is configured, `search()`
/// runs both FTS and vector queries and fuses the results using Reciprocal Rank
/// Fusion. Without an embedder, `search()` falls back to FTS-only (M6b behavior).
pub struct PgMemoryStore {
    pool: Pool,
    /// Present when an `OPENAI_API_KEY` is configured. `None` = FTS-only search.
    embedder: Option<Arc<dyn EmbeddingProvider>>,
}

impl PgMemoryStore {
    /// Create a store with FTS-only search. Backward-compatible with M6b callers.
    pub fn new(pool: Pool) -> Self {
        Self {
            pool,
            embedder: None,
        }
    }

    /// Create a store with hybrid search enabled.
    pub fn with_embedder(pool: Pool, embedder: Arc<dyn EmbeddingProvider>) -> Self {
        Self {
            pool,
            embedder: Some(embedder),
        }
    }

    fn pool_err(e: impl std::fmt::Display) -> CherubError {
        CherubError::Storage(format!("pool error: {e}"))
    }

    fn query_err(e: impl std::fmt::Display) -> CherubError {
        CherubError::Storage(format!("query error: {e}"))
    }

    /// Try to embed `text`. Returns `None` on failure (logs a warning) so that
    /// callers can degrade gracefully rather than failing the entire operation.
    async fn try_embed(&self, text: &str) -> Option<Vec<f32>> {
        let embedder = self.embedder.as_ref()?;
        match embedder.embed(text).await {
            Ok(v) => Some(v),
            Err(e) => {
                tracing::warn!(error = %e, "embedding failed, storing without vector");
                None
            }
        }
    }

    /// FTS search: returns `RankedResult`s with 1-based positional rank.
    async fn fts_search(
        &self,
        conn: &tokio_postgres::Client,
        query: &str,
        scope: Option<MemoryScope>,
        user_id: Option<&str>,
        limit: usize,
    ) -> Result<Vec<RankedResult>, CherubError> {
        let mut conditions: Vec<String> = vec![
            "superseded_by IS NULL".to_owned(),
            "tsv @@ plainto_tsquery('english', $1)".to_owned(),
        ];
        let mut params: Vec<Box<dyn tokio_postgres::types::ToSql + Sync + Send>> =
            vec![Box::new(query.to_owned())];
        let mut idx: usize = 2;

        if let Some(s) = scope {
            conditions.push(format!("scope = ${idx}"));
            params.push(Box::new(s.as_str().to_owned()));
            idx += 1;
        }
        if let Some(uid) = user_id {
            conditions.push(format!("user_id = ${idx}"));
            params.push(Box::new(uid.to_owned()));
            idx += 1;
        }

        let where_clause = conditions.join(" AND ");
        let sql = format!(
            "SELECT id, confidence FROM memories \
             WHERE {where_clause} \
             ORDER BY ts_rank(tsv, plainto_tsquery('english', $1)) DESC \
             LIMIT ${idx}"
        );
        params.push(Box::new(limit as i64));

        let param_refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = params
            .iter()
            .map(|p| p.as_ref() as &(dyn tokio_postgres::types::ToSql + Sync))
            .collect();

        let rows = conn
            .query(sql.as_str(), &param_refs)
            .await
            .map_err(Self::query_err)?;

        Ok(rows
            .iter()
            .enumerate()
            .map(|(i, row)| RankedResult {
                memory_id: row.get("id"),
                rank: i + 1,
                confidence: row.get::<_, f32>("confidence"),
            })
            .collect())
    }

    /// Vector search: returns `RankedResult`s ordered by cosine distance.
    /// Returns an empty vec if no embedder is configured or embedding fails.
    async fn vector_search(
        &self,
        conn: &tokio_postgres::Client,
        query: &str,
        scope: Option<MemoryScope>,
        user_id: Option<&str>,
        limit: usize,
    ) -> Result<Vec<RankedResult>, CherubError> {
        let query_vec = match self.try_embed(query).await {
            Some(v) => Vector::from(v),
            None => return Ok(Vec::new()),
        };

        let mut conditions: Vec<String> = vec![
            "superseded_by IS NULL".to_owned(),
            "embedding IS NOT NULL".to_owned(),
        ];
        let mut params: Vec<Box<dyn tokio_postgres::types::ToSql + Sync + Send>> =
            vec![Box::new(query_vec)];
        let mut idx: usize = 2;

        if let Some(s) = scope {
            conditions.push(format!("scope = ${idx}"));
            params.push(Box::new(s.as_str().to_owned()));
            idx += 1;
        }
        if let Some(uid) = user_id {
            conditions.push(format!("user_id = ${idx}"));
            params.push(Box::new(uid.to_owned()));
            idx += 1;
        }

        let where_clause = conditions.join(" AND ");
        let sql = format!(
            "SELECT id, confidence FROM memories \
             WHERE {where_clause} \
             ORDER BY embedding <=> $1 \
             LIMIT ${idx}"
        );
        params.push(Box::new(limit as i64));

        let param_refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = params
            .iter()
            .map(|p| p.as_ref() as &(dyn tokio_postgres::types::ToSql + Sync))
            .collect();

        let rows = conn
            .query(sql.as_str(), &param_refs)
            .await
            .map_err(Self::query_err)?;

        Ok(rows
            .iter()
            .enumerate()
            .map(|(i, row)| RankedResult {
                memory_id: row.get("id"),
                rank: i + 1,
                confidence: row.get::<_, f32>("confidence"),
            })
            .collect())
    }

    /// Bulk-load full `Memory` rows by a list of IDs in one query.
    /// Returns rows in the order specified by `ids` (preserves RRF score order).
    async fn load_memories_by_ids(
        &self,
        conn: &tokio_postgres::Client,
        ids: &[Uuid],
    ) -> Result<Vec<Memory>, CherubError> {
        if ids.is_empty() {
            return Ok(Vec::new());
        }

        let rows = conn
            .query(
                &format!("SELECT {MEMORY_COLUMNS} FROM memories WHERE id = ANY($1)"),
                &[&ids],
            )
            .await
            .map_err(Self::query_err)?;

        // Build an id→Memory map then reorder according to the input slice.
        let by_id: std::collections::HashMap<Uuid, Memory> = rows
            .iter()
            .map(|row| map_row(row).map(|m| (m.id, m)))
            .collect::<Result<_, _>>()?;

        Ok(ids.iter().filter_map(|id| by_id.get(id).cloned()).collect())
    }
}

/// Standard column list for SELECT queries that produce a `Memory`.
const MEMORY_COLUMNS: &str = "id, user_id, scope, category, path, content, structured, \
     source_session_id, source_turn_number, source_type, confidence, \
     created_at, updated_at, last_referenced_at, superseded_by";

/// Map a postgres `Row` to a `Memory` struct. Parses TEXT enum columns from strings.
fn map_row(row: &tokio_postgres::Row) -> Result<Memory, CherubError> {
    let scope_str: &str = row.get("scope");
    let category_str: &str = row.get("category");
    let source_type_str: &str = row.get("source_type");

    // REAL column in PG maps to f32 in tokio-postgres.
    let confidence: f32 = row.get("confidence");

    Ok(Memory {
        id: row.get("id"),
        user_id: row.get::<_, String>("user_id"),
        scope: scope_str.parse()?,
        category: category_str.parse()?,
        path: row.get::<_, String>("path"),
        content: row.get::<_, String>("content"),
        structured: row.get("structured"),
        source_session_id: row.get("source_session_id"),
        source_turn_number: row.get("source_turn_number"),
        source_type: source_type_str.parse()?,
        confidence,
        created_at: row.get("created_at"),
        updated_at: row.get("updated_at"),
        last_referenced_at: row.get("last_referenced_at"),
        superseded_by: row.get("superseded_by"),
    })
}

#[async_trait]
impl MemoryStore for PgMemoryStore {
    async fn store(&self, memory: NewMemory) -> Result<Uuid, CherubError> {
        // Embed before acquiring a connection so we don't hold pool connections during HTTP.
        let embedding = self.try_embed(&memory.content).await.map(Vector::from);

        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        let row = conn
            .query_one(
                "INSERT INTO memories \
                 (user_id, scope, category, path, content, structured, \
                  source_session_id, source_turn_number, source_type, confidence, embedding) \
                 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) \
                 RETURNING id",
                &[
                    &memory.user_id,
                    &memory.scope.as_str(),
                    &memory.category.as_str(),
                    &memory.path,
                    &memory.content,
                    &memory.structured,
                    &memory.source_session_id,
                    &memory.source_turn_number,
                    &memory.source_type.as_str(),
                    &memory.confidence,
                    &embedding,
                ],
            )
            .await
            .map_err(Self::query_err)?;

        Ok(row.get(0))
    }

    async fn recall(&self, filter: MemoryFilter) -> Result<Vec<Memory>, CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Build WHERE clauses dynamically. Always exclude superseded records.
        // Each param is boxed into a type-erased ToSql so we can mix types.
        let mut conditions: Vec<String> = vec!["superseded_by IS NULL".to_owned()];
        let mut params: Vec<Box<dyn tokio_postgres::types::ToSql + Sync + Send>> = Vec::new();
        let mut idx: usize = 1;

        if let Some(scope) = filter.scope {
            conditions.push(format!("scope = ${idx}"));
            params.push(Box::new(scope.as_str().to_owned()));
            idx += 1;
        }
        if let Some(cat) = filter.category {
            conditions.push(format!("category = ${idx}"));
            params.push(Box::new(cat.as_str().to_owned()));
            idx += 1;
        }
        if let Some(prefix) = filter.path_prefix {
            conditions.push(format!("path LIKE ${idx}"));
            params.push(Box::new(format!("{prefix}%")));
            idx += 1;
        }
        if let Some(uid) = filter.user_id {
            conditions.push(format!("user_id = ${idx}"));
            params.push(Box::new(uid));
            idx += 1;
        }

        let limit = filter.limit.unwrap_or(10);
        let where_clause = conditions.join(" AND ");
        let sql = format!(
            "SELECT {MEMORY_COLUMNS} FROM memories \
             WHERE {where_clause} \
             ORDER BY created_at DESC \
             LIMIT ${idx}"
        );
        params.push(Box::new(limit));

        let param_refs: Vec<&(dyn tokio_postgres::types::ToSql + Sync)> = params
            .iter()
            .map(|p| p.as_ref() as &(dyn tokio_postgres::types::ToSql + Sync))
            .collect();

        let rows = conn
            .query(sql.as_str(), &param_refs)
            .await
            .map_err(Self::query_err)?;

        rows.iter().map(map_row).collect()
    }

    async fn search(
        &self,
        query: &str,
        scope: Option<MemoryScope>,
        user_id: Option<&str>,
        limit: i64,
    ) -> Result<Vec<Memory>, CherubError> {
        let config = SearchConfig::default();
        let pre_limit = config.pre_fusion_limit;
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Run FTS and vector searches concurrently — both use the same connection
        // pool, so we need separate connections. We can reuse `conn` for FTS and
        // get a second connection for vector.
        let fts_results = self
            .fts_search(&conn, query, scope, user_id, pre_limit)
            .await?;

        let vector_results = if self.embedder.is_some() {
            // Embed before acquiring another connection.
            let conn2 = self.pool.get().await.map_err(Self::pool_err)?;
            self.vector_search(&conn2, query, scope, user_id, pre_limit)
                .await?
        } else {
            Vec::new()
        };

        let scored = reciprocal_rank_fusion(&fts_results, &vector_results, &config, limit as usize);

        let ids: Vec<Uuid> = scored.iter().map(|r| r.memory_id).collect();
        self.load_memories_by_ids(&conn, &ids).await
    }

    async fn update(&self, id: Uuid, changes: MemoryUpdate) -> Result<Uuid, CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Load the existing memory to carry forward unchanged fields.
        let existing = conn
            .query_one(
                &format!("SELECT {MEMORY_COLUMNS} FROM memories WHERE id = $1"),
                &[&id],
            )
            .await
            .map_err(Self::query_err)?;
        let base = map_row(&existing)?;

        let new_content = changes
            .content
            .as_deref()
            .unwrap_or(&base.content)
            .to_owned();
        let new_structured = changes.structured.or(base.structured);
        let new_confidence = changes.confidence.unwrap_or(base.confidence);

        // Re-embed new content before inserting (embedding happens before holding conn).
        drop(conn);
        let embedding = self.try_embed(&new_content).await.map(Vector::from);
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Insert new row (DB assigns fresh uuidv7 ID).
        let new_row = conn
            .query_one(
                "INSERT INTO memories \
                 (user_id, scope, category, path, content, structured, \
                  source_session_id, source_turn_number, source_type, confidence, embedding) \
                 VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) \
                 RETURNING id",
                &[
                    &base.user_id,
                    &base.scope.as_str(),
                    &base.category.as_str(),
                    &base.path,
                    &new_content,
                    &new_structured,
                    &base.source_session_id,
                    &base.source_turn_number,
                    &base.source_type.as_str(),
                    &new_confidence,
                    &embedding,
                ],
            )
            .await
            .map_err(Self::query_err)?;
        let new_id: Uuid = new_row.get(0);

        // Chain the superseded_by pointer on the old row.
        conn.execute(
            "UPDATE memories SET superseded_by = $1, updated_at = now() WHERE id = $2",
            &[&new_id, &id],
        )
        .await
        .map_err(Self::query_err)?;

        Ok(new_id)
    }

    async fn forget(&self, id: Uuid) -> Result<(), CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        // Soft-delete: set superseded_by = self as sentinel (preserves audit trail).
        conn.execute(
            "UPDATE memories SET superseded_by = id, updated_at = now() WHERE id = $1",
            &[&id],
        )
        .await
        .map_err(Self::query_err)?;

        Ok(())
    }

    async fn touch(&self, id: Uuid) -> Result<(), CherubError> {
        let conn = self.pool.get().await.map_err(Self::pool_err)?;

        conn.execute(
            "UPDATE memories SET last_referenced_at = now() WHERE id = $1",
            &[&id],
        )
        .await
        .map_err(Self::query_err)?;

        Ok(())
    }
}
